sudo: required
language: objective-c
osx_image: xcode9.4.1
rvm:
- 2.5.1
cache:
  timeout: 86400 # 1 day
  directories:
  - /home/travis/cache/
  - /home/travis/.rvm/
before_install:
- chmod a+x ./Scripts/auth.sh
- chmod a+x ./Scripts/build_docs.sh
- chmod a+x ./Scripts/build_package.sh
- chmod a+x ./Scripts/deauth.sh
- chmod a+x ./Scripts/install_pandoc.sh
- chmod a+x ./Scripts/install_unity.sh
- chmod a+x ./Scripts/test.sh
install:
- ./Scripts/install_unity.sh
script:
# - ./Scripts/auth.sh
- ./Scripts/test.sh
# - ./Scripts/deauth.sh
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then make build; fi
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $ACCESS_KEY
  bucket: candycoded
  local-dir: build
  upload-dir: build
  skip_cleanup: true
  on:
    branch: master
